Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoderThoughtsBlog.Data;
using CoderThoughtsBlog.Models;
using CoderThoughtsBlog.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace CoderThoughtsBlog.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly UserManager<BlogUser> _userManager;

        public BlogsController(ApplicationDbContext context, IImageService imageService, UserManager<BlogUser> userManager)
        {
            _context = context;
            _imageService = imageService;
            _userManager = userManager;
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Blogs.Include(b => b.BlogUser);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.BlogUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Image")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                blog.Created = DateTime.UtcNow;
                //Set the current user to the BlogUserId (Security and necessity)
                blog.BlogUserId = _userManager.GetUserId(User);

                //Convert the image into a byte array.
                blog.ImageData = await _imageService.EncodeImageAsync(blog.Image);
                blog.ContentType = _imageService.ContentType(blog.Image);

                _context.Add(blog);

                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Blog blog, IFormFile? newImage)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var editBlog = await _context.Blogs.FindAsync(blog.Id);
                    editBlog.Updated = DateTime.UtcNow;
                    if(editBlog.Name != blog.Name)
                    {
                        editBlog.Name = blog.Name;
                    }
                    if(editBlog.Description != blog.Description)
                    {
                        editBlog.Description = blog.Description;
                    }
                    if(newImage is not null)
                    {
                        editBlog.ImageData = await _imageService.EncodeImageAsync(newImage);
                        editBlog.ContentType= newImage.ContentType;
                    }






                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.BlogUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.Id == id);
        }
    }
}

Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoderThoughtsBlog.Data;
using CoderThoughtsBlog.Models;
using CoderThoughtsBlog.Services;
using CoderThoughtsBlog.Services.Interfaces;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Identity;
using System.Reflection.Metadata;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using X.PagedList;
using CoderThoughtsBlog.ViewModels;
using MailKit.Search;

namespace CoderThoughtsBlog.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ISlugService _slugService;
        private readonly IImageService _imageService;
        private readonly UserManager<BlogUser> _userManager;
        private readonly BlogSearchService _blogSearchService;


        public PostsController(ApplicationDbContext context, ISlugService slugService, IImageService imageService, UserManager<BlogUser> userManager, BlogSearchService blogSearchService)
        {
            _context = context;
            _slugService = slugService;
            _imageService = imageService;
            _userManager = userManager;
            _blogSearchService = blogSearchService;
        }

        // GET: Posts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Posts.Include(p => p.Blog).Include(p => p.BlogUser);
            return View(await applicationDbContext.ToListAsync());
        }


        [Authorize]
        // GET: Posts
        public async Task<IActionResult> BlogPostIndex(int? id, int? page)
        {
            if (id is null)
            {
                return NotFound();
            }

            var pageNumber = page ?? 1;
            var pageSize = 5;

            //var posts = _context.Posts.Where(p => p.BlogId == id);
            var posts = await _context.Posts
                                .Where(p => p.BlogId == id && p.ReadyStatus == Enums.ReadyStatus.ProductionReady)
                                .Include(p => p.BlogUser)
                                .OrderByDescending(p => p.Created)
                                .ToPagedListAsync(pageNumber, pageSize);

            return View(posts);
        }

        public async Task<IActionResult> SearchIndex(int? page, string? searchTerm)
        {
            ViewData["SearchTerm"] = searchTerm;

            var pageNumber = page ?? 1;
            var pageSize = 6;

            var posts = _blogSearchService.Search(searchTerm);

            return View(await posts.ToPagedListAsync(pageNumber, pageSize));


        }

        //public async Task<IActionResult> TagIndex(int? page, string? tag)
        //{
        //    if (tag is null)
        //    {
        //        return NotFound();
        //    }

        //    var pageNumber = page ?? 1;
        //    var pageSize = 6;

            //var tags = _tagSearchService.Search(tag);
            //var posts = _blogSearchService.TagSearch();

            //return View(await posts.ToPagedListAsync(pageNumber, pageSize));


            //var posts = _context.Posts.Where(p => p.BlogId == id);
            //var posts = await _context.Posts
            //                          .Include(p => p.Tags)
            //                          .ThenInclude(p => p.Text)
            //                          .OrderByDescending(p => p.Updated)
            //                          .ToPagedListAsync(pageNumber, pageSize);



            //.Tags
            //.Where(t => t.Text == tag)
            //.Include(t => t.Post)
            //.OrderByDescending(p => p.Post.Updated)
            //.ToPagedListAsync(pageNumber, pageSize);

            //return View(posts);
        //}


        // GET: Posts/Details/5
        public async Task<IActionResult> Details(string slug)
        {
            ViewData["Title"] = "Post Details Page";

            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Blog)
                .Include(p => p.BlogUser)
                .Include(p => p.Tags)
                .Include(p => p.Comments)
                .ThenInclude(c => c.BlogUser)
                .Include(c => c.Comments)
                .ThenInclude(c => c.Moderator)
                .FirstOrDefaultAsync(m => m.Slug == slug);

            var comment = await _context.Comments.Distinct().ToListAsync();

            if (post == null)
            {
                return NotFound();
            }

            var dataVM = new PostDetailsViewModel()
            {
                Post = post,
                Tags = _context.Tags
                               .Select(t => t.Text.ToLower())
                               .Distinct()
                               .ToList(),
                Comment = comment


            };

            ViewData["HeaderImage"] = _imageService.DecodeImage(post.ImageData, post.ContentType);
            ViewData["MainText"] = post.Title;
            ViewData["SubText"] = post.Abstract;

            return View(dataVM);
        }

        // GET: Posts/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogId,Title,Abstract,Content,ReadyStatus,Image")] Post post, List<string> tagValues)
        {
            if (ModelState.IsValid)
            {
                //Create the slug and determine if it is unique
                var slug = _slugService.UrlFriendly(post.Title);
                var newSlug = post.Slug;
                //Create a variable to store whether an error has occurred
                var validationError = false;

                //post.Slug = slug;

                //Detect if incoming Slug is null
                if (string.IsNullOrEmpty(slug))
                {
                    validationError = true;
                    ModelState.AddModelError("Title", "The Title cannot be used as it results in an empty slug.");
                }

                //Detect incoming duplicate Slugs
                else if (!_slugService.IsUnique(slug))
                {
                    validationError = true;
                    ModelState.AddModelError("Title", "The title you provided cannot be used as it results in a duplicate slug.");
                }


                if (validationError)
                {
                    ViewData["TagValues"] = string.Join(",", tagValues);
                    ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name");
                    return View(post);
                }

                post.Slug = slug;

                post.Created = DateTime.UtcNow;
                //Set the current user to the BlogUserId (Security and necessity)
                var authorId = _userManager.GetUserId(User);
                post.BlogUserId = authorId;

                //Convert the image into a byte array.
                post.ImageData = await _imageService.EncodeImageAsync(post.Image);
                post.ContentType = _imageService.ContentType(post.Image);

                _context.Add(post);
                await _context.SaveChangesAsync();

                //Loop over the incoming list of tagValues.
                foreach (var tagText in tagValues)
                {
                    _context.Add(new Tag()
                    {
                        PostId = post.Id,
                        BlogUserId = authorId,
                        Text = tagText
                    });
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name", post.BlogId);

            return View(post);
        }

        // GET: Posts/TagIndex/tagtext


        // GET: Posts/Edit/slug
        [Authorize]
        public async Task<IActionResult> Edit(string slug)
        {
            if (slug == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.Include(p => p.Tags).FirstOrDefaultAsync(p => p.Slug == slug);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name", post.BlogId);
            ViewData["TagValues"] = string.Join(",", post.Tags.Select(t => t.Text));

            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BlogId,Title,Abstract,Content,ReadyStatus")] Post post, IFormFile? NewImage, List<string> tagValues)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                try
                {
                    var newPost = await _context.Posts.Include(p => p.Tags).FirstOrDefaultAsync(p => p.Id == post.Id);

                    newPost.Updated = DateTime.UtcNow;

                    if (post.Title is not null)
                    {

Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>The About Page</h1>

Views/Home/Contact.cshtml
@using CoderThoughtsBlog.ViewModels;
@model ContactMe

<div class="container mt-2">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
            <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
            <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
            <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
            <form asp-action="Contact">
                <div class="control-group">
                    <div class="form-group floating-label-form-group controls">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" type="text" class="form-control" placeholder="Name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="control-group">
                    <div class="form-group floating-label-form-group controls">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" type="email" class="form-control" placeholder="Email Address" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label asp-for="Phone"></label>
                        <input type="tel" asp-for="Phone" class="form-control" placeholder="Phone Number" required data-validation-required-message="Please enter your phone number.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label asp-for="Subject">Subject</label>
                        <input asp-for="Subject" class="form-control" placeholder="Subject" required data-validation-required-message="Please enter your phone number.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="control-group">
                    <div class="form-group floating-label-form-group controls">
                        <label asp-for="Message"></label>
                        <textarea asp-for="Message" id="summernote" rows="5" class="form-control" required data-validation-required-message="Please enter a message."></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <br>
                <div id="success"></div>
                <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    <script>
        $('#summernote').summernote({
            placeholder: 'Message...',
            tabsize: 2,
            height: 120,
            toolbar: [
              ['style', ['style']],
              ['font', ['bold', 'underline', 'clear']],
              ['color', ['color']],
              ['para', ['ul', 'ol', 'paragraph']],
              ['table', ['table']],
              ['insert', ['link', 'picture', 'video']],
              ['view', ['fullscreen', 'codeview', 'help']]
            ]
          });
    </script>



}

Views/Home/Index.cshtml
@using CoderThoughtsBlog.Models
@using CoderThoughtsBlog.Services
@using CoderThoughtsBlog.Services.Interfaces
@using CoderThoughtsBlog.Enums;

@using Microsoft.AspNetCore.Identity;

@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

@inject IImageService _imageService;
@inject UserManager<BlogUser> _userManager;

@model IPagedList<Blog>;

@{
    ViewData["Title"] = "Coder Thoughts Blog";
    ViewData["MainText"] = "Coder Thoughts";
    ViewData["SubText"] = "The things we think of...";
    Layout = "~/Views/Shared/_LayoutLander.cshtml";
}
<div class="container">
    <div class="row">

        @foreach (var blog in Model)
        {
            <div class="col-sm-12 col-md-6 col-lg-4 mt-2">
                <div class="card">
                    <img class="card-img-top" src="@_imageService.DecodeImage(blog.ImageData, blog.ContentType)" />
                    <div class="card-body text-center">

                        <div class="card-title-color">
                            <hr class="card-hr" />
                            <h5 class="card-title">@blog.Name</h5>
                            <hr class="card-hr"/>
                        </div>

                        <div>
                            <p class="card-text cftooltip" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-original-title="@blog.Description">
                                @blog.Description
                            </p>
                        </div>

                        <br />

                        <div class="text-center">
                            <a class="btn btn-dark btn-sm form-control mb-2" asp-action="BlogPostIndex" asp-controller="Posts" asp-route-id="@blog.Id">
                                Read Posts
                            </a>
                        </div>

                        @if (User.IsInRole(BlogRole.Administrator.ToString()))
                        {
                            <div class="text-center">
                                <a class="btn btn-dark form-control btn-sm mb-2" asp-action="Create" asp-controller="Posts" asp-route-id="@blog.Id">Create Post</a>
                            </div>
                        }

                        @if (User.IsInRole(BlogRole.Administrator.ToString()))
                        {
                            <div class="text-center">
                                <a class="btn btn-dark btn-sm mb-2 form-control" asp-action="Edit" asp-controller="Blogs" asp-route-id="@blog.Id">Edit Blog</a>
                            </div>
                        }




                    </div>
                </div>
            </div>
        }

    </div>
</div>

<!--Add Paging Controls Here-->
<div class="row">
    <div class="col h3 ms-2">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    </div>
</div>
<div class="row">
    <div class="col ms-2">
        @Html.PagedListPager(Model, page => Url.Action("Index",new {page = page}),
        new PagedListRenderOptionsBase
        {
        LiElementClasses = new string[] { "page-item" },
        PageClasses = new string[] { "page-link" }
        })        
    </div>
</div>


@section Scripts {
    <script>
        var swaMsg = '@TempData["SweetAlert"]'
        if (swalMsg != "") {
            Swal.fire({
            icon: 'success',
            title: swalMsg,
            timer: 2500
            })
        }

        $(document).ready(function () {
            $("p").tooltip();
        });
    </script>
}